
# 第5章


パッケージの呼び出し．

```{r}
#| message: false
library(tidyverse)
library(magrittr)
library(gnm)
library(broom)
```


モデル適合度を表示するための関数を準備する．すべてgnmによって推定を行う．

```{r}
# Specify the constrasts
# Here, we use sum to zero contrast.
options(width=90, contrasts = c(factor="contr.sum", ordered="contr.treatment"))

# Define a function which calculation BIC based on L2 statistics
model.summary <- function(obj, Model = NULL){
  if (sum(class(obj) == "gnm") != 1)
    stop("estimate with gnm")
  aic <- obj$deviance - obj$df * 2 # AIC(L2)
  bic <- obj$deviance - obj$df * log(sum(obj$y)) #BIC(L2)
  delta <- 100 * sum(abs(obj$y - obj$fitted.values)) / (2 * sum(obj$y))
  p <- pchisq(obj$deviance, obj$df, lower.tail = FALSE)     #p<-ifelse(p<0.001,"<0.001",p)
  result <- matrix(0, 1, 7)
  if (is.null(Model)){ 
  Model <- deparse(substitute(obj))
  }
  result <- tibble(
    "Model Description" = Model,
    "df" = obj$df,
    "L2" = obj$deviance,
    #"AIC(L2)" = aic,
    "BIC" = bic,
    "Delta" = delta,
    "p" = p
  )
  return(result)
}

```


## 表5.1
```{r}
# Table 5.1
Freq <- c(118, 28,  32,  6,  7,
        218, 28,  97, 12, 14,
         11,  2,   4,  1,  1,
        104, 22,  61,  8,  5,
        117, 24,  70,  9,  7,
         42,  6,  20,  2,  0,
         48, 16, 104, 14,  9,
        128, 52,  81, 14, 12)

worries <- gl(8,5)
situations <- gl(5,1,8*5)

tab5.1 <- tibble(Freq, worries, situations)

# Model 1 - Independence
m1 <- tab5.1 |> 
  gnm(Freq ~ worries + situations,
      family = poisson,
      trace = F,
      tolerance = 1e-12,
      data = _)
model.summary(m1)

# Model 2 - RC(1)
m2 <- tab5.1 |> 
  gnm(Freq ~ worries + situations + Mult(1, worries, situations),
      family = poisson,
      trace = F,
      tolerance = 1e-12,
      data = _)
model.summary(m2)

# Model 3 - RC(1) with equality constraints on
# MIL=ECO=MTO, ENR=SAB=OTH and ASAF=IFAA
worries.a <- worries
levels(worries.a) <- factor(c(1, 2, 2, 3, 3, 2, 4, 3))
worries.a
situations.a <- situations
levels(situations.a) <- factor(c(1, 2, 3, 3, 4))
situations.a

m3.un <- tab5.1 |> 
  gnm(Freq ~ worries + situations + 
        Mult(1, worries.a, situations.a), 
           family = poisson,
           trace = F, 
           tolerance = 1e-12,
      data = _)
model.summary(m3.un)

mu <- getContrasts(m3.un, 
                 pickCoef(m3.un, "[.]worries.a"),
                 ref = c(1, 3, 3, 1) / 8, scaleRef = c(1, 3, 3, 1) / 8,
                 scaleWeights = c(1, 3, 3, 1))
nu <- getContrasts(m3.un, 
                 pickCoef(m3.un, "[.]situations.a"),
                 ref = c(1, 1, 2, 1) / 5, scaleRef = c(1, 1, 2, 1) / 5,
                 scaleWeights = c(1, 1, 2, 1))

con <- c(mu$qvframe[, 1][c(1, 4)], nu$qvframe[, 1][c(1, 4)])
m3 <- gnm(Freq ~ worries + situations + Mult(1, worries.a, situations.a), 
          family = poisson,
          constrain = c(14, 17, 18, 21), constrainTo = con,
          trace = F, 
          tolerance = 1e-12)
summary(m3);mu;nu;model.summary(m3.un)

# Model 4 - RC(1) with equality constraints on
# MIL=ECO=MTO=ENR=SAB=OTH and ASAF=IFAA
worries.b <- worries
levels(worries.b) <- factor(c(1, 2, 2, 2, 2, 2, 3, 2))
worries.b

m4.un <- tab5.1 |> 
  gnm(Freq ~ worries + situations + Mult(1, worries.b, situations.a), 
           family = poisson,
           trace = F, 
           tolerance = 1e-12,
      data = _)
model.summary(m4.un)

# Model 5
m5.un <- tab5.1 |> 
  gnm(Freq ~ worries + situations + 
        Mult(1, worries, situations, inst = 1) + 
        Mult(1, worries, situations, inst = 2), 
      family = poisson,
      trace = F, tolerance = 1e-12,
      data = _)
model.summary(m5.un)

# Model 6 - RC(2) with equality constraints on
# ECO=MTO=MIL=ENR=SAB and ASAF=IFAA in both dimensions
worries.c <- worries
levels(worries.c) <- factor(c(1,2,2,2,2,2,3,4))
worries.c

set.seed(12345)
m6.un <- tab5.1 |> 
  gnm(Freq ~ worries + situations + 
        Mult(1, worries.c, situations.a, inst = 1) + 
        Mult(1, worries.c, situations.a, inst = 2), 
      family = poisson,
      trace = F, 
      tolerance = 1e-12,
      data = _)
model.summary(m6.un)
```


## 表5.4

最適尺度法として連関モデルを利用する．

```{r}
# Table 5.4
Freq<-c(1096,  1847,  1255,  925,    3321,  6123,  6830,  5524,
        1541,  3134,  3145, 3300,    1915,  4429,  7035,  9421,
        4183,  5139,  1857, 1272,    8080,  8586,  4788,  4294,
        6033,  9211,  5046, 1058,   28130, 44589, 20074,  3408,
        4354, 13430, 18670, 9821,    2250,  9075, 18286, 14358,
       14587, 31470, 16390, 3751,    8242, 17532, 12825,  3956,
        1517,  5820,  6197, 2372,     721,  2909,  4141,  2070,
        3581,  9268,  5463, 1007,    1341,  3808,  3163,   815,
        1454,  3109,  1055,  888,     563,  1909,  1018,  1051,
        3237,  3851,   377,  102,     731,   858,   247,    84,
       14882, 22182,  5363, 1136,   11650, 15818,  5524,  2122,
        6033,  3475,    63,   18,    1603,  1005,    30,    16,
        
        5968,  8783,  7701, 6483,    8733, 14329, 19386, 28143,
        1011,  2162,  3536, 6649,     697,  1299,  2362, 10796,
        3214,  3621,  2485, 3177,     793,  1134,  1292,  3597,
       11532, 16837,  6975, 1839,    2563,  2995,  2060,  1600,
        1009,  2719,  3521, 3409,     296,   503,   626,  1273,
        1586,  3025,  1726,  668,     245,   415,   238,   218,
         387,   941,   564,  316,      86,   138,    79,    48,
         994,  1988,   542,  145,     158,   259,   101,    56,
         171,   409,   223,  245,      65,   172,    99,   174,
         293,   290,    67,   31,      32,    62,    18,    30,
        4288,  4916,  1452,  766,     616,   794,   347,   300,
         370,   186,     3,    4,      67,    37,     5,     2)

income <- gl(4, 1, 192)  # 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 ...
occ <- gl(12, 8, 192)  # 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 ...
edu1 <- rep(c(1,2), each = 4, length.out = 96)
edu2 <- rep(c(3,4), each = 4, length.out = 96)
educ <- c(edu1, edu2) |> factor()

# 確認
matrix(income, nrow = 24, ncol = 8, byrow = TRUE)
matrix(occ, nrow = 24, ncol = 8, byrow = TRUE)
matrix(educ, nrow = 24, ncol = 8, byrow = TRUE)

# 分析用データ
tab5.4 <- data.frame(Freq, income, occ, educ)
########################################################################################

# Table 5.5
# Model 1: Complete Independence
m1 <- tab5.4 |> 
  gnm(Freq ~ educ + occ + income, 
          data = _, 
          family = poisson, 
          tolerance = 1e-12)
model.summary(m1) 

# Model 2: Conditional Independence
m2 <- tab5.4 |> 
  gnm(Freq ~ educ * occ + income * occ, 
          data = _, 
          family = poisson, 
          tolerance = 1e-12)
model.summary(m2)

# Model 3: All two-way interaction
m3 <- tab5.4 |> 
  gnm(Freq ~ educ * occ + income * occ + educ * income, 
          data = _, 
          family = poisson, tolerance = 1e-12)
model.summary(m3)

# Model 4: RC(1)+RL(1) partial association
m4 <- tab5.4 |> 
  gnm(Freq ~ educ + occ + income + Mult(1, occ, educ) + Mult(1, occ, income),
          data = _, 
          family = poisson,
          tolerance = 1e-12)
model.summary(m4)

# Model 5: Model 4 with consistent row (occupation) scores
m5 <- tab5.4 |> 
  gnm(Freq ~ educ + occ + income + Mult(1, occ, educ + income),
          data = _, 
          family = poisson, 
          tolerance = 1e-12)
model.summary(m5)
mu <- getContrasts(model = m5, 
                   set = pickCoef(m5, "[.]occ")[1:12],
                   ref = "mean", 
                   scaleRef = "mean", 
                   scaleWeights = "unit")
mu

# Model 6: RC(1)+RL(1)+CL(1) partial association
m6 <- tab5.4 |> 
  gnm(Freq ~ educ + occ + income + 
        Mult(1, occ, educ) + 
        Mult(1, occ, income) +
        Mult(1, educ, income),
      data = _, 
      family = poisson, 
      tolerance = 1e-12)
model.summary(m6)

# Model 7: Model 6 with consistent row (occupation) scores
m7 <- tab5.4 |> 
  gnm(Freq ~ educ + occ + income + 
        Mult(1, occ, educ + income) + 
        Mult(1, educ, income),
      data = _, 
      family = poisson, 
      tolerance = 1e-12)
model.summary(m7)
mu <- getContrasts(model = m7, 
                   set = pickCoef(m7, "[.]occ"),
                   ref = "mean", 
                   scaleRef = "mean", 
                   scaleWeights = "unit")
mu
		
# Model 8: model 6 with consistent row, column and layer scores
# currently, this might not be fitted with gnm!
```


- 表5.5のモデル1については原著および訳書ともに$\Delta$の値が間違っているので注意すること（印刷後に修正漏れに気づきました）．実際は`r model.summary(m1)$Delta |> round(2)`である．

```{r}
# 2つの引数についてのリストを作成
## 第1引数はモデル
models <- list(m1, m2, m3, m4, m5, m6, m7)
## 第2引数はモデルの内容
model_desctiption <- 
  list("完全独立", 
       "条件付き独立", 
       "すべての2元交互作用",
       "RC(1)+RL(1) 部分連関",
       "一貫した行(職業)スコアのあるRC(1)+RL(1) 部分連関",
       "RC(1)+RL(1)+CL(1) 部分連関",
       "一貫した行(職業)スコアのあるRC(1)+RL(1)+CL(1)部分連関")
# 結果をまとめる
map2_dfr(models, model_desctiption, model.summary, .id = "Model") |> 
  knitr::kable()
```

